package xadrez.jv.cliente;

import java.awt.Image;

import javax.swing.ImageIcon;


public class MenuPrincipal extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	/**
	 * @brief CLASSE PARA O MENU PRINCIPAL
	 * */
	
    /**
     * Creates new form ChessFrame
     */
    public MenuPrincipal() {
        initComponents();
        PreencheMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CapturadasBrancas1 = new javax.swing.JPanel();
        MenuLateral = new javax.swing.JPanel();
        Menu = new javax.swing.JLabel();
        Explicavel = new javax.swing.JButton();
        Simulacao = new javax.swing.JButton();
        Capa = new javax.swing.JLabel();

        CapturadasBrancas1.setBackground(new java.awt.Color(255, 255, 255));
        CapturadasBrancas1.setPreferredSize(new java.awt.Dimension(100, 50));
        CapturadasBrancas1.setLayout(new java.awt.GridLayout(1, 8));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        MenuLateral.setBackground(new java.awt.Color(255, 255, 255));

        Menu.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        Menu.setText("XADREZ");

        Explicavel.setBackground(new java.awt.Color(48, 58, 68));
        Explicavel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        Explicavel.setForeground(new java.awt.Color(255, 255, 255));
        Explicavel.setText("mODO EXPLICÁVEL");
        Explicavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExplicavelActionPerformed(evt);
            }
        });

        Simulacao.setBackground(new java.awt.Color(186, 186, 186));
        Simulacao.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        Simulacao.setForeground(new java.awt.Color(48, 58, 68));
        Simulacao.setText("MODO SIMULAÇÃO");
        Simulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimulacaoActionPerformed(evt);
            }
        });

        Capa.setText("A");

        javax.swing.GroupLayout MenuLateralLayout = new javax.swing.GroupLayout(MenuLateral);
        MenuLateral.setLayout(MenuLateralLayout);
        MenuLateralLayout.setHorizontalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Simulacao)
                            .addComponent(Explicavel)))
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(Capa, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        MenuLateralLayout.setVerticalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Explicavel)
                        .addGap(51, 51, 51)
                        .addComponent(Simulacao))
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(Capa, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(225, 225, 225))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulacaoActionPerformed
        dispose();
        ModoSimulacao.main(null);
    }//GEN-LAST:event_SimulacaoActionPerformed

    private void ExplicavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExplicavelActionPerformed
        dispose();
        ModoExplicavel.main(null);
    }//GEN-LAST:event_ExplicavelActionPerformed

      private void PreencheMenu(){
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/Chess_img/Teste.png"));  
        Image originalImage = originalIcon.getImage();
        Image scaledImage = originalImage.getScaledInstance(515, 306, Image.SCALE_SMOOTH);  
        ImageIcon MenuIcon = new ImageIcon(scaledImage);
        Capa.setIcon(MenuIcon);
      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    		
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Capa;
    private javax.swing.JPanel CapturadasBrancas1;
    private javax.swing.JButton Explicavel;
    private javax.swing.JLabel Menu;
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JButton Simulacao;
    // End of variables declaration//GEN-END:variables
}
