package xadrez.jv.cliente;

import java.awt.Color;
import java.awt.Image;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import javax.swing.Timer;

import xadrez.jv.backend.Bispo;
import xadrez.jv.backend.Cavalo;
import xadrez.jv.backend.Peca;
import xadrez.jv.backend.Tabuleiro;
import xadrez.jv.backend.Torre;
import xadrez.jv.servidor.*;
import xadrez.jv.servidor.enuns.Tipo;

public class ModoExplicavel extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	/** @brief CLASSE PARA O JOGO NO MODO EXPLICAVEL */
	
	private static Tabuleiro t = new Tabuleiro();
    /**
     * Creates new form ChessFrame
     */
    public ModoExplicavel() {
        initComponents();
        drawChessBoard();
        PreencheLetras();
        PreencheNumeros();
        PreencheMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CapturadasBrancas1 = new javax.swing.JPanel();
        MenuLateral = new javax.swing.JPanel();
        AddBispo = new javax.swing.JButton();
        Menu = new javax.swing.JLabel();
        AddTorre = new javax.swing.JButton();
        AddCavalo = new javax.swing.JButton();
        Bispo = new javax.swing.JLabel();
        Torre = new javax.swing.JLabel();
        Cavalo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Sair = new javax.swing.JLabel();
        Tabuleiro = new javax.swing.JPanel();
        Numericas = new javax.swing.JPanel();
        Letras = new javax.swing.JPanel();
        CapturadasBrancas = new javax.swing.JPanel();
        CapturadasPretas = new javax.swing.JPanel();

        CapturadasBrancas1.setBackground(new java.awt.Color(255, 255, 255));
        CapturadasBrancas1.setPreferredSize(new java.awt.Dimension(100, 50));
        CapturadasBrancas1.setLayout(new java.awt.GridLayout(1, 8));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(214, 217, 224));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        MenuLateral.setBackground(new java.awt.Color(255, 255, 255));

        AddBispo.setBackground(new java.awt.Color(204, 204, 204));
        AddBispo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        AddBispo.setText("eXPLICAR Bispo");
        AddBispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBispoActionPerformed(evt);
            }
        });

        Menu.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        Menu.setText("MENU:");

        AddTorre.setBackground(new java.awt.Color(204, 204, 204));
        AddTorre.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        AddTorre.setText("eXPLICAR  Torre");
        AddTorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTorreActionPerformed(evt);
            }
        });

        AddCavalo.setBackground(new java.awt.Color(204, 204, 204));
        AddCavalo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        AddCavalo.setText("eXPLICAR  Cavalo");
        AddCavalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCavaloActionPerformed(evt);
            }
        });

        Bispo.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jButton1.setText("Sair do Jogo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLateralLayout = new javax.swing.GroupLayout(MenuLateral);
        MenuLateral.setLayout(MenuLateralLayout);
        MenuLateralLayout.setHorizontalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bispo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Torre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cavalo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddBispo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddTorre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddCavalo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        MenuLateralLayout.setVerticalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBispo)
                    .addComponent(Bispo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Torre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTorre))
                .addGap(18, 18, 18)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cavalo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCavalo))
                .addGap(18, 18, 18)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(434, 434, 434))
        );

        Tabuleiro.setBackground(new java.awt.Color(255, 255, 255));
        Tabuleiro.setPreferredSize(new java.awt.Dimension(500, 400));
        Tabuleiro.setLayout(new java.awt.GridLayout(8, 8));

        Numericas.setBackground(new java.awt.Color(255, 255, 255));
        Numericas.setPreferredSize(new java.awt.Dimension(100, 400));
        Numericas.setLayout(new java.awt.GridLayout(8, 1));

        Letras.setBackground(new java.awt.Color(255, 255, 255));
        Letras.setPreferredSize(new java.awt.Dimension(25, 100));
        Letras.setLayout(new java.awt.GridLayout(1, 8));

        CapturadasBrancas.setBackground(new java.awt.Color(214, 217, 224));
        CapturadasBrancas.setPreferredSize(new java.awt.Dimension(100, 50));
        CapturadasBrancas.setLayout(new java.awt.GridLayout(1, 8));

        CapturadasPretas.setBackground(new java.awt.Color(214, 217, 224));
        CapturadasPretas.setPreferredSize(new java.awt.Dimension(100, 50));
        CapturadasPretas.setLayout(new java.awt.GridLayout(1, 8));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Letras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CapturadasPretas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Numericas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Tabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CapturadasBrancas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 708, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(CapturadasPretas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Letras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numericas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CapturadasBrancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** @brief Personaliza o textArea da explicação.
     * @return Um scrollPane com a mensagem a ser exibida.
     * */
    private JScrollPane personalizeMessage(String mensagem)
    {
    	 JTextArea textArea = new JTextArea(5, 30); // 5 linhas, 30 colunas
         textArea.setText(mensagem);
         textArea.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12));
         textArea.setWrapStyleWord(true);
         textArea.setLineWrap(true);
         textArea.setCaretPosition(0);
         textArea.setEditable(false);
         
         JScrollPane scrollPane = new JScrollPane(textArea);
         
         return scrollPane;
    }
    
    /** @brief Usado para capturar a imagem correta a ser usada na simulação do tabueiro
     * @return O icone correspondente a peça solicitada.
     * */
    public ImageIcon genarateChessIcon(Peca p)
    {
    	ImageIcon originalIcon;
    	Image originalImage;
    	Image scaledImage;
    	ImageIcon chessIcon;
    	
    	if (p instanceof Bispo) {
	    	originalIcon = new ImageIcon(getClass().getResource("/Chess_img/Bispo.png"));  
	        originalImage = originalIcon.getImage();
	        scaledImage = originalImage.getScaledInstance(30, 30, Image.SCALE_SMOOTH);  
	        chessIcon = new ImageIcon(scaledImage);
    	}else if (p instanceof Cavalo) {
    		originalIcon = new ImageIcon(getClass().getResource("/Chess_img/Cavalo.png")); 
            originalImage = originalIcon.getImage();
            scaledImage = originalImage.getScaledInstance(26, 42, Image.SCALE_SMOOTH);  
            chessIcon = new ImageIcon(scaledImage);
    	}else {
    		originalIcon = new ImageIcon(getClass().getResource("/Chess_img/Torre.png")); 
            originalImage = originalIcon.getImage();
            scaledImage = originalImage.getScaledInstance(26, 42, Image.SCALE_SMOOTH);  
            chessIcon = new ImageIcon(scaledImage);
    	}
    	return chessIcon;
    }
    
    /**
     * @brief Simula a movimentação de uma peça 
     * */
    public void simulateMovement(Peca p, int[] destinos) {
    	/** Variaveis declaradas como final para uso dentro do escopo do 'timer'
    	 * Necessária a implemetação do vetor para que os valores possam ser alterados.
    	 * */
    	final Timer[] timer = new Timer[1];
    	final boolean[] contador = {true}; //Usado para saber quando posionar ou movimentar a peça
    	final int[] indices = {0, 1}; //Indices para o vetor de destinos
    	
    	t.limparTabuleiro();
    	
        timer[0] = new Timer(1500, e->{
        	if (contador[0])
        	{
        		t.setPeca(p);
	            drawChessBoard();
	            contador[0] = false;
        	}else if (indices[1] <= 5)
        	{
        		final boolean isValid = t.movimentarPeca(destinos[indices[0]], destinos[indices[1]], p.getId());
            	indices[0]+=2; 
            	indices[1]+=2;
            	
            	if (isValid)
                	drawChessBoard();
                else {
                	JOptionPane.showMessageDialog(null, "Movimento Inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
        	}else {
        		timer[0].stop();
        	}
        });
        
        timer[0].setInitialDelay(0);
        timer[0].start();
    }
    
    /** @brief Mostra a explicação e, caso o usuário queira, chama uma função para simular 
     * uma movimentação de uma peça. 
     * */
    private void AddBispoActionPerformed(java.awt.event.ActionEvent evt) {
        solicitarExplicacao("BISPO", new Bispo(0, 0, 1));
    }

    private void AddTorreActionPerformed(java.awt.event.ActionEvent evt) {
        solicitarExplicacao("TORRE", new Torre(0, 0, 1));
    }
    private void AddCavaloActionPerformed(java.awt.event.ActionEvent evt) {
        solicitarExplicacao("CAVALO", new Cavalo(0, 0, 1));
    }

    /** @brief Handler do botão para sair do jogo. Retorna para o menu Principal*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        t.limparTabuleiro();
        MenuPrincipal.main(null);
    }

    private void drawChessBoard() {
        Tabuleiro.removeAll(); // Limpar o painel antes de desenhar o tabuleiro
        // Adicionar linhas do tabuleiro
        for (int row = 0; row < 8; row++) {
           
            for (int col = 0; col < 8; col++) {
                JLabel cell = new JLabel("", SwingConstants.CENTER);
                cell.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                boolean isWhite = (row + col) % 2 == 0;
                if (!t.isEmpty(row, col))
                	cell.setIcon(genarateChessIcon(t.getMatrizPosicao(row, col)));
                else if (isWhite) 
                    cell.setBackground(Color.WHITE);
                else
                    cell.setBackground(Color.BLACK);
                cell.setOpaque(true);
                Tabuleiro.add(cell);
            }
        }
        Tabuleiro.revalidate();
       Tabuleiro.repaint();
    }

     private void PreencheLetras() {
        Letras.removeAll(); // Limpar o painel antes de desenhar o tabuleiro
        // Adicionar linhas do tabuleiro
              for (char col = 'A'; col <= 'H'; col++) {
                JLabel cell = new JLabel("", SwingConstants.CENTER);
                //cell.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                cell.setText(String.valueOf(col));
                cell.setForeground(Color.BLACK);
                cell.setOpaque(true);
                Letras.add(cell);
            }
       Letras.revalidate();
       Letras.repaint();
    }

      private void PreencheNumeros() {
        Numericas.removeAll(); // Limpar o painel antes de desenhar o tabuleiro
        // Adicionar linhas do tabuleiro
              for (int row = 1; row <= 8; row++) {
                JLabel cell = new JLabel("", SwingConstants.CENTER);
                //cell.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                cell.setText(String.valueOf(row));
                cell.setForeground(Color.BLACK);
                cell.setOpaque(true);
                Numericas.add(cell);
            }
       Numericas.revalidate();
       Numericas.repaint();
    }
      
    private void PreencheMenu(){
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/Chess_img/Bispo.png"));  
        Image originalImage = originalIcon.getImage();
        Image scaledImage = originalImage.getScaledInstance(30, 30, Image.SCALE_SMOOTH);  
        ImageIcon MenuIcon = new ImageIcon(scaledImage);
        Bispo.setIcon(MenuIcon);
        
        originalIcon = new ImageIcon(getClass().getResource("/Chess_img/Torre.png")); 
        originalImage = originalIcon.getImage();
        scaledImage = originalImage.getScaledInstance(26, 42, Image.SCALE_SMOOTH);  
        MenuIcon = new ImageIcon(scaledImage);
        Torre.setIcon(MenuIcon);
        
        originalIcon =new ImageIcon(getClass().getResource("/Chess_img/Cavalo.png")); 
        originalImage = originalIcon.getImage();
        scaledImage = originalImage.getScaledInstance(26, 42, Image.SCALE_SMOOTH);  
        MenuIcon = new ImageIcon(scaledImage);
        Cavalo.setIcon(MenuIcon);
        
        originalIcon =new ImageIcon(getClass().getResource("/Chess_img/Sair.png"));
        originalImage = originalIcon.getImage();
        scaledImage = originalImage.getScaledInstance(42, 42, Image.SCALE_SMOOTH);  
        MenuIcon = new ImageIcon(scaledImage);
        Sair.setIcon(MenuIcon);
    }

    private void solicitarExplicacao(String nome_peca, Peca peca_local){
        RequestProtocol req = new RequestProtocol();
        req.setTipo(Tipo.GET_EXP);
        req.setPeca(nome_peca);
        ResponseProtocol response = client.request(req);
        String mensagem = (response.getMensagem() != null) ? response.getMensagem() : "Erro ao buscar explicação da peça desejada!!";
        JScrollPane scrollPane = personalizeMessage(mensagem);
        scrollPane.setPreferredSize(new java.awt.Dimension(350, 150));

        int opc = JOptionPane.showConfirmDialog(this, scrollPane, nome_peca, JOptionPane.OK_CANCEL_OPTION);
        if (opc == JOptionPane.OK_OPTION) {
            Integer[] destinosSrv = response.getDestinosSimulacao();
            int[] destinos = null;
            if (destinosSrv != null) {
                destinos = new int[destinosSrv.length];
                for (int i = 0; i < destinosSrv.length; i++) destinos[i] = destinosSrv[i];
            }
            if (destinos != null) simulateMovement(peca_local, destinos);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoExplicavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoExplicavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoExplicavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoExplicavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModoExplicavel().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBispo;
    private javax.swing.JButton AddCavalo;
    private javax.swing.JButton AddTorre;
    private javax.swing.JLabel Bispo;
    private javax.swing.JPanel CapturadasBrancas;
    private javax.swing.JPanel CapturadasBrancas1;
    private javax.swing.JPanel CapturadasPretas;
    private javax.swing.JLabel Cavalo;
    private javax.swing.JPanel Letras;
    private javax.swing.JLabel Menu;
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JPanel Numericas;
    private javax.swing.JLabel Sair;
    private javax.swing.JPanel Tabuleiro;
    private javax.swing.JLabel Torre;
    private javax.swing.JButton jButton1;
    private final Client client = new Client("localhost", 8089);
    // End of variables declaration//GEN-END:variables
}
